### ISSUE TITLE
cant sign out

### ISSUE THREAD

**Issue by DIVYANSH2005** [Tustin/PlayStationDiscord#123] opened 2020-12-02 16:09 UTC
cant sign out after the new ps5 update yall did

**Comment by albo44** [comment] 2020-12-28 10:05
same i have that issue as well

**Comment by JustJoshua666** [comment] 2021-01-17 14:28
I have the same problem. I did delete all the datas, but the problem is too. I want to sign out, but there is no reaction. Hope it will be fixed soon.

**Closed** 2021-02-23 23:11 UTC
