### ISSUE TITLE
Error Logging in 

### ISSUE THREAD

**Issue by nanamizono** [Tustin/PlayStationDiscord#80] opened 2020-02-13 13:46 UTC
So I just installed PlaystationDiscord and I tried to log in with my account and I got this error
![Screenshot_1](https://user-images.githubusercontent.com/61015011/74441137-9a94c980-4e6f-11ea-821c-e205531ba925.png)

What am I supposed to do?

**Comment by AsmodeusShadows** [comment] 2020-02-20 20:01
I am having the same issue and I noticed after trying to log in the program itself has a messed up image, I also just downloaded and installed it as well.
<img width="58" alt="playstation discord issue" src="https://user-images.githubusercontent.com/61293276/74973652-6bd79f80-53e9-11ea-8623-1a782f8c711b.PNG">

**Comment by Jaynator495** [comment] 2020-02-21 00:37
I'm also having this problem...
![image](https://user-images.githubusercontent.com/13039635/74993247-42c20980-53ff-11ea-9fd1-50191c3f2f0f.png)

**Comment by AngryKiller** [comment] 2020-02-23 14:18
Update to version 3.1.1: https://github.com/Tustin/PlayStationDiscord/releases/tag/v3.1.1

**Comment by ryandanger** [comment] 2020-02-23 14:20
> Update to version 3.1.1: https://github.com/Tustin/PlayStationDiscord/releases/tag/v3.1.1

Nope. Doesn't work. This issue was created after 3.1.1 was released too.

**Comment by AngryKiller** [comment] 2020-02-23 14:38
> > Update to version 3.1.1: https://github.com/Tustin/PlayStationDiscord/releases/tag/v3.1.1
> 
> Nope. Doesn't work. This issue was created after 3.1.1 was released too.

I first had the issue because I downloaded version 3.1.0 (the one linked on the official website), and updating to 3.1.1 fixed it for me, it's weird that you still have this issue

**Comment by Tustin** [comment] 2020-02-23 18:28
This is caused by Akamai's anti-bot protection. I thought I had fixed this in the latest update, but for some reason it's not working for everyone. I don't really have any clue what is triggering it and I don't really have a lot of free time to try to figure it out.

**Comment by YouGotHitByGunner** [comment] 2020-02-25 11:24
I have the same issue.

**Comment by Dawg-z** [comment] 2020-03-07 19:20
Hope the issue can get fixed soon!

**Comment by darnelldibbles** [comment] 2020-03-08 03:09
Having same issue on Mac as well

**Comment by BriluZz** [comment] 2020-03-16 12:53
hello i still have this bug. will be settled in the future? or is there a technique to log in?

**Comment by Rin-Okumura** [comment] 2020-03-19 14:46
Having the same exact issue on Windows 10. Hopefully Tustin will find a way to fix it eventually.

**Comment by Rin-Okumura** [comment] 2020-03-23 00:59
It works now.

**Comment by Rin-Okumura** [comment] 2020-03-23 14:34
Now it doesn't work again. It's weird.

**Comment by Kiznel** [comment] 2020-03-25 18:34
Uninstall, then delete PlayStationDiscord directory from AppData\Roaming.

Should work (at least temporarily) after reinstalling 3.1.1

**Comment by Tustin** [comment] 2020-03-25 20:26
I've also heard some success with using 3.0.2 (no idea why; I didn't change any code in the login window between that update at 3.1.0). You can try that and see if the login works. It shouldn't auto update until you actually login but once you logged in you should stay logged in for a long time unless you delete the program cache.

**Comment by KrazeOooga** [comment] 2020-03-27 01:14
someone link 3.0.2 download plz

**Comment by bkt7396** [comment] 2020-03-28 17:04
@KrazeOooga 
https://github.com/Tustin/PlayStationDiscord/releases/tag/3.0.2


3.0.2 is working for me, although it has an "auto update failed" I was still able to authenticate and login

**Comment by KrazeOooga** [comment] 2020-03-28 22:27
@bkt7396 Thanks!! working

**Comment by Cyan101** [comment] 2020-03-30 13:24
Any word on why this hasn't been working? Happy to try PR and fix if I get pointed in the right dircetion

**Comment by Rabio1** [comment] 2020-04-02 03:43
> Any word on why this hasn't been working? Happy to try PR and fix if I get pointed in the right dircetion
> 
> 3.0.2 lets me login but doesnt show in discord

this worked for me gj finding this

**Comment by Gamewizard** [comment] 2020-04-04 00:56
![Screenshot_20200403_205539](https://user-images.githubusercontent.com/2892983/78415087-865a8680-75ed-11ea-81eb-98c6101f5953.png)
I have been having the same issue under Linux. Can't login to my PSN account.

**Comment by Anonymous42456** [comment] 2020-04-05 17:04
Same thing happening to me 
![image](https://user-images.githubusercontent.com/20717186/78504922-f8da7c00-773d-11ea-929e-bdb759bc528c.png)

**Comment by zeina99** [comment] 2020-04-05 19:10
I have the same problem

**Comment by ohhsodead** [comment] 2020-04-05 23:13
@Gamewizard From trying another app that uses the same method for login as this, it also has the exact same error. I guess something is wrong with PS servers for now, and maybe will be fixed soon?

**Comment by Gamewizard** [comment] 2020-04-06 04:16
@ohhsodead  This was what I initially suspected until I signed in through my browser fine. Even tried a different browser from my normal one to verify a cached cookie was not allowing me to still sign in while there where other issues going on but I singed in fine in the other browser when I was trying to get this up and running.

**Comment by Tustin** [comment] 2020-04-10 21:44
I pushed a new version that downgrades Electron to the version I used in PlayStationDiscord 3.0.2 and below (which seemed to have some success for people). Please try it and let me know if you can login 😄. https://github.com/Tustin/PlayStationDiscord/releases/tag/v3.1.2

**Comment by Rin-Okumura** [comment] 2020-04-10 23:33
> I pushed a new version that downgrades Electron to the version I used in PlayStationDiscord 3.0.2 and below (which seemed to have some success for people). Please try it and let me know if you can login 😄. https://github.com/Tustin/PlayStationDiscord/releases/tag/v3.1.2

Thanks, man. It works fine for now. I'll keep you informed.

**Comment by Diamond-10** [comment] 2020-04-14 14:40
So the 3.1.2 version works for me on Windows, but not on Mac.

**Comment by shadowfreak16** [comment] 2020-04-17 09:46
> I pushed a new version that downgrades Electron to the version I used in PlayStationDiscord 3.0.2 and below (which seemed to have some success for people). Please try it and let me know if you can login 😄. https://github.com/Tustin/PlayStationDiscord/releases/tag/v3.1.2

Hello. Sorry, it didn't work for my Mac :<

**Comment by zeina99** [comment] 2020-04-17 10:37
> So the 3.1.2 version works for me on Windows, but not on Mac.

I tried it on my mac, and it works just fine.

**Comment by zeina99** [comment] 2020-04-18 14:09
ok nevermind, for some reason i was logged out and logging in doesn't work anymore

**Comment by Rin-Okumura** [comment] 2020-04-24 12:23
> I pushed a new version that downgrades Electron to the version I used in PlayStationDiscord 3.0.2 and below (which seemed to have some success for people). Please try it and let me know if you can login 😄. https://github.com/Tustin/PlayStationDiscord/releases/tag/v3.1.2

Hey man. 2 weeks later and still no problem. Works perfectly. Thank you.

**Comment by SpennyLoaf** [comment] 2020-04-27 00:17
Still getting a server issue signing in with v3.1.2 https://imgur.com/Ck5b7jb

**Comment by ninoM** [comment] 2020-05-16 14:20
Also still getting this on `3.1.2` on Windows 10.
![image](https://user-images.githubusercontent.com/2021570/82121995-74126180-97c3-11ea-9f19-9cf0f586ee36.png)

**Comment by kamiqaze** [comment] 2020-05-17 16:26
on mac 10.13.6. the latest release is not working for me, either. even tried older releases, no luck.

**Comment by juyeonies** [comment] 2020-05-21 17:00
Hello! (first of all, english is not my first language so I apologize for any mistakes...)

Some people were also facing login problems on the official PS4 Remote Play program on Windows and the trick that solved the issue was to change the url on the login page from "https://id.sonyentertainmentnetwork.com/signin/" to "https://my.account.sony.com/central/signin/". 
Could this maybe fix this issue on PlaystationDiscord too?

I was using the 3.0.2 version just fine but my account logged out and now I can't login on any version anymore.

**Comment by Tustin** [comment] 2020-06-28 14:32
@juyeonies Not having much luck with your new link. It just says "An error has occurred." when I open the page.

**Comment by MsMystic** [comment] 2021-01-01 19:21
I get the same error too (using a Mac), tried to download the older version as well didn't work. Hope that there is going to be a fix soon...

**Comment by Russkingking** [comment] 2021-03-12 20:28
I'm having this issue with the newest version, I want to use the new version so I can have the PS5 support.

**Comment by CharTex** [comment] 2021-03-12 22:02
Can confirm this issue is still occurring on the latest release.

**Comment by CharTex** [comment] 2021-03-12 23:33
Alright, Maybe have found the cause of the issue and a temporary solution.

By changing the required electron version in the package.json to 6.0.0 then rebuilding the software using the given instructions, I was able to login successfully. The software seems to work perfectly fine after doing this as well.

So I think it is definitely something to do with later Electron versions.
It is very odd, especially as the software worked fine on my machine before I re-installed my operating system.

Just thought I should document this in-case anybody else wants to give it a try.

**Comment by joshlopes** [comment] 2021-03-18 13:18
![image](https://user-images.githubusercontent.com/3440849/111632444-631feb80-87ec-11eb-85e0-e8da5469f2d9.png)

For whatever is worthy i get this issue when attempting to login in the last version and 3.1.2 on MAC

**Comment by joshlopes** [comment] 2021-03-18 13:27
@CharTex Do you mind create a PR with the changes to the packages.json you just did ?

**Comment by joshlopes** [comment] 2021-03-18 13:49
Oh i see this library uses an hacked listened URL from the official app, the link: https://my.account.sony.com/central/signin/?response_type=code&app_context=inapp_ios&device_profile=mobile&extraQueryParams=%7B%0A%20%20%20%20PlatformPrivacyWs1%20%3D%20minimal%3B%0A%7D&token_format=jwt&access_type=offline&scope=psn%3Amobile.v1%20psn%3Aclientapp&service_entity=urn%3Aservice-entity%3Apsn&ui=pr&smcid=psapp%253Asettings-entrance&darkmode=true&redirect_uri=com.playstation.PlayStationApp%3A%2F%2Fredirect&support_scheme=sneiprls&client_id=ac8d161a-d966-4728-b0ea-ffec22f69edc&duid=0000000d0004008088347AA0C79542D3B656EBB51CE3EBE1&device_base_font_size=10&elements_visibility=no_aclink&service_logo=ps&auth_ver=v3&error=login_required&error_code=4165&error_description=User+is+not+authenticated&no_captcha=false&cid=41fbd168-62d2-4b1b-8214-661045f16c1d#/signin/ca?entry=ca

Is not working anymore, you will need to grab the new one :)

**Comment by Tustin** [comment] 2021-03-18 14:23
@joshlopes That first URL you linked is new actually. They started using it for the login in the new mobile app a few months ago. The login issue described here really has nothing to do with what login endpoint you use. Sony utilizes anti-bot scripts made by Akamai, which seems to be very strict and for some reason will give false-positives that result in this error. You can Google that specific error message to see normal PlayStation users getting that error in a regular browser.

I've tried many things to circumvent it but it honestly just seems random. I've had times where the login works fine for me and other times I'll get that error too. I think the only solution is to hope that Sony either removes those scripts or tones them down a bit so they aren't as aggressive.

**Comment by joshlopes** [comment] 2021-03-19 09:45
@Tustin thank you, if we use the auth v2 from 3.0.2 would that not work with what we currently have? Do we need the new "stuff" from oauth v3? Because the scripts and anti bot scripts you mention seem to not exist in v2, i can login just fine.

**Comment by SpencerFerret** [comment] 2021-03-20 17:46
I can get it to sign in on 3.1.2 but as soon as I update it says I need to refresh my authorization tokens. I've tried quite a few time hoping to get that one lucky time it works, but now I give up

**Comment by Verequies** [comment] 2021-04-03 13:29
For me the latest commit doesn't compile however the previous commit works. I can change the required electron version to 8.5.5 and I am able to logon and everything works successfully :D

**Closed** 2022-01-31 20:27 UTC
Labels: bug
