### ISSUE TITLE
PlaystationDiscord is not working!

### ISSUE THREAD

**Issue by xKiraw** [Tustin/PlayStationDiscord#82] opened 2020-02-27 21:29 UTC
Hi there!

I have a problem with PlaystationDiscord. When I start the program, a window opens in which I should log in with my Playstation account. I enter the account details and then I get an error message.

Can I fix that somehow?

Sincerely yours,
Kiraw

**Comment by ohhsodead** [comment] 2020-02-27 23:00
Possible duplicate of #80

**Closed** 2020-02-27 23:40 UTC
Labels: bug
